services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/workspaces:cached
    command: sleep infinity
    env_file:
      - ../.env
      - ../packages/example/.env
